# Generated by Django 4.1.7 on 2023-02-27 01:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0005_favourt_delete_favourite'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='favourt',
            new_name='Favourite',
        ),
        migrations.RenameField(
            model_name='favourite',
            old_name='users',
            new_name='user',
        ),
    ]
